# Starting with Numpy

In [2]:
import numpy as np

In [4]:
#Creating Array
a = np.array([0,1,2,3,6,4,5,7,9])
a

array([0, 1, 2, 3, 6, 4, 5, 7, 9])

In [5]:
#Printing the dimensions of array
a.ndim

1

In [6]:
#Printing the shape of array i.e rows and columns
a.shape

(9,)

### 2-Dimensional Array

In [14]:
# 2-Dimensional array
b = np.array([[0,1,2],[2,3,4]])
b

array([[0, 1, 2],
       [2, 3, 4]])

In [15]:
b.shape

(2, 3)

In [16]:
b.ndim

2

In [17]:
len(b)

2

### 3-Dimensional Array

In [18]:
# 3-Dimensional array
x = np.array([[[2,3],[7,8]],[[1,2],[0,1]]])
x

array([[[2, 3],
        [7, 8]],

       [[1, 2],
        [0, 1]]])

In [21]:
x.shape

(2, 2, 2)

In [22]:
x.ndim

3

In [23]:
len(x)

2

In [25]:
#Creating Array with the help of functions
#With the help of arange function
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
#Here we are taking the elements from 1 to 20 but skipping 3 items every time, so 1 is the starting point, 20 is the end point and 3 is the number of items to be skipped.
arr2 = np.arange(1,20,3)
arr2

array([ 1,  4,  7, 10, 13, 16, 19])

In [33]:
#Here 0 is the starting point, 2 is the end point and 8 is the number of items generated in between this range.
arr3 = np.linspace(0,2,8)
arr3

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [36]:
#Here ones is used to generate n-dimensional array with every element as one.
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
#Here zeros is used to generate n-dimensional array with every element as zero.
arr5 = np.zeros((2,2))
arr5

array([[0., 0.],
       [0., 0.]])

In [4]:
#Here eye is used to generate a m*n matrix with diagonal element as 1
arr6 = np.eye(3,2)
arr6


array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [6]:
#Creating array with diagonal function
arr7 = np.diag([1,4,2,3])
arr7

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [7]:
#Genearting Array with random function and parameter passed is the number of random number to be generated.
arr8 = np.random.rand(5)
arr8

array([0.84137886, 0.41228427, 0.86564764, 0.07789559, 0.55607557])

### Some basic data types in Numpy 

In [8]:
#dtype is used to define the data type of the item

arr9 = np.arange(10,dtype="float64")
arr9

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
arr9.dtype

dtype('float64')

In [11]:
#Complex data type
arr10 = np.array([2+7j,5+7j])
arr10.dtype

dtype('complex128')

In [13]:
#Boolean data type
arr11 = np.array([True,False,True])
arr11.dtype

dtype('bool')

In [17]:
#Unicode data type
arr12 = np.array(["aaaaaa","bbbbb","ccccc"])
arr12.dtype

dtype('<U6')

## Indexing and slicing

In [19]:
#Printing 5th index
a = np.arange(10)
print(a[5])

5


In [20]:
#Printing index for multi-dimensional array
a = np.diag([2,3,4])
print(a[2,2])

4


In [21]:
#Assigning value 
a[2,1] = 6
a

array([[2, 0, 0],
       [0, 3, 0],
       [0, 6, 4]])

In [23]:
 b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
#Slicing from 1 to 7
b[1:7]

array([1, 2, 3, 4, 5, 6])

In [25]:
#Slicing from 1 to 15 and skipping 2 items every time
b[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [26]:
#Combining assignment and slicing
b[15:] = 0
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  0,
        0,  0,  0])

### Copies and views

In [28]:
#shares_memory is used to check whether 2 arrays shares same memory block or not.
arrA = np.arange(20)
arrB = arrA[::2]
np.shares_memory(arrA,arrB)

True

In [29]:
#copy() is used to create a force copy
arrC = arrA[::2].copy()
np.shares_memory(arrA,arrC)

False